### ISSUE TITLE
.ruby-env cannot handle spaces in quotes strings without escaping them

### ISSUE THREAD

**Issue by trevmex** [wayneeseguin/rvm#3236]
The following results in an error, if put in your .ruby-env file:

    JRUBY_OPTS="-Xcli.debug=true --debug"

The error is ```-bash: export: `--debug': not a valid identifier```.

To fix this, I had to escape the space in the .ruby-env file like so:

    JRUBY_OPTS="-Xcli.debug=true\ --debug"

I'd like to not have to do this.

**Comment by mpapis** [comment]
so after adding tests I found that the supported format right now is **without quotes**, like this:
```bash
JRUBY_OPTS=-Xcli.debug=true --debug
```
when you add quotes the string is double quoted which means the quoting is canceled ... need to add detection of the quotes and avoid double quoting in that case.

by double quoted I mean:
```bash
JRUBY_OPTS=""-Xcli.debug=true --debug""
```
that's why the space had to be escaped.

**Comment by trevmex** [comment]
Got it! Good to know. thanks for the fast turnaround as always, mpapis!
