### ISSUE TITLE
stat: illegal option -- c

### ISSUE THREAD

**Issue by horaceho** [wayneeseguin/rvm#3239]
A new rvm installation on OSX Yosemite:
```
$ \curl -sSL https://get.rvm.io | bash -s stable
Downloading https://github.com/wayneeseguin/rvm/archive/1.26.7.tar.gz
Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.7/1.26.7.tar.gz.asc
Found PGP signature at: 'https://github.com/wayneeseguin/rvm/releases/download/1.26.7/1.26.7.tar.gz.asc',
but no GPG software exists to validate it, skipping.

Installing RVM to /Users/horace/.rvm/
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
    RVM PATH line found in /Users/horace/.bashrc /Users/horace/.zshrc.
    RVM sourcing line found in /Users/horace/.bash_profile /Users/horace/.zprofile.
Installation of RVM in /Users/horace/.rvm/ is almost complete:

  * To start using RVM you need to run `source /Users/horace/.rvm/scripts/rvm`
    in all your open shell windows, in rare cases you need to reopen all shell windows.

```

**Comment by mpapis** [comment]
please try with `rvm get head`

**Comment by mpapis** [comment]
also if it still fails for someone please show me:
```bash
echo $_system_type
rvm info system
```

**Comment by jsaraiva** [comment]
Still happens on Yosemite (on Mavericks it goes fine):
-------------------------
meserver:~ jsaraiva$ \curl -sSL https://get.rvm.io | sudo bash 
Password:
Downloading https://github.com/wayneeseguin/rvm/archive/master.tar.gz
tar: Failed to set default locale

Installing RVM to /usr/local/rvm/
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
test -f /etc/profile.d/rvm.sh && source /etc/profile.d/rvm.sh
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
Installation of RVM in /usr/local/rvm/ is almost complete:

  * First you need to add all users that will be using rvm to 'rvm' group,
    and logout - login again, anyone using rvm will be operating with `umask u=rwx,g=rwx,o=rx`.

  * To start using RVM you need to run `source /etc/profile.d/rvm.sh`
    in all your open shell windows, in rare cases you need to reopen all shell windows.

# jsaraiva,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: http://rvm.io/help and https://twitter.com/rvm_io
meserver:~ jsaraiva$ echo $_system_type
Darwin
meserver:~ jsaraiva$ rvm info system

system:

  system:
    uname:       "Darwin DefineServer.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64"
    system:      "osx/10.10/x86_64"
    bash:        "/bin/bash => GNU bash, version 3.2.53(1)-release (x86_64-apple-darwin14)"
    zsh:         "/bin/zsh => zsh 5.0.5 (x86_64-apple-darwin14.0)"
meserver:~ jsaraiva$ 
-------------------------

I used sudo on purpose, as I want to make a multi-user install. However, I don't believe that is the root of the problem here.

Thanks in advance!

**Comment by mpapis** [comment]
ok need to debug, please run:
```bash
\curl -sSL https://get.rvm.io | sudo bash -s head --trace 2>&1 | tee big.log
```
and [gist](https://gist.github.com) `big.log`

**Comment by jsaraiva** [comment]
OK, done. You can find the gist here:
https://gist.github.com/anonymous/9b1456d6a9b53b7e42d2

**Comment by mpapis** [comment]
this should do it, try:
```bash
\curl -sSL https://get.rvm.io | sudo bash -s head
```

**Comment by jsaraiva** [comment]
Yep, the installation works like a charm now!
Thanks!

**Comment by jsaraiva** [comment]
Sorry to write in this closed ticket, but this may be related to the fix: when installing ruby 2.2.0, I get a lot of the following message:
/usr/local/rvm/scripts/functions/detect_system: line 202: __rvm_db: command not found
(see https://gist.github.com/jsaraiva/3323d9c246788071c683 for the complete listing)

Nevertheless, the installation does continue, and finishes successfully, so apparently no harm done. :-)

Thanks again!

**Comment by mpapis** [comment]
it's fixed, run `rvm get head`

**Comment by jsaraiva** [comment]
Confirmed, the message no longer appears.
Thanks again!
