### ISSUE TITLE
RVM install stuck while importing gemset global.gems

### ISSUE THREAD

**Issue by VarunWachaspati** [wayneeseguin/rvm#3344]
![screenshot from 2015-03-13 18 37 41](https://cloud.githubusercontent.com/assets/7585096/6638937/c9631e90-c9b0-11e4-8e22-e3150e59d2c9.png)

Here is the screenshot of my terminal. Has been there since an hour.
Tried a few times still get the same result.
kindly help out

**Comment by havenwood** [comment]
We tracked this down to DNS timeouts on irc. It was reproducible with system Ruby.

**Comment by karldotm** [comment]
VarunWachaspati,

Some questions:

1. You say that the rvm install gets stuck - are you doing a fresh install of rvm or an upgrade?
2. Are you performing this system wide or just for a single account?
3. What is the full curl command you are using to initiate the rvm install?
4. Do you have any gems already installed on the system or the account running the rvm install?

The binary for ubuntu/14.10/x86_64/ruby-2.2.1 is available - repeat your rvm install attempt and see if this completes using the precompiled version of ruby.

If you continue to have issues please follow these steps and email me the output (as text rather than screenshots please.)

1. Run the rvm install with --trace but without including the installation of ruby or other components
2. Install ruby-2.2.1 using **rvm install 2.2.1 --trace**

**Comment by mpapis** [comment]
I'm using `dnsmasq` to avoid such problems - closing as RVM can not help in fix it.
